name: Haskell
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Haskell
        run: |
          sudo apt-get update
          sudo apt-get install -y haskell-platform
      - name: Install dependencies
        run: |
          cabal update
          cabal install persistent persistent-sqlite
      - name: Run Haskell script
        run: cabal run
