name: Haskell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Haskell
      uses: haskell/actions/setup-haskell@v1
      with:
        ghc-version: 'latest'
        cabal-version: 'latest'

    - name: Install dependencies
      run: cabal update && cabal install persistent persistent-sqlite

    - name: Build and run
      run: cabal run
